mysql:
  hostname: '192.168.226.128'
  port: '3306'
  dbname: 'school'
  username: 'root'
  password: 'Aa@123456'

gin:
  host: '0.0.0.0'
  port: '80'

log:
  outputfile: false
  logname: 'music.log'
  logprefix: '[love-music]'