mysql:
  hostname: '192.168.226.128'
  port: '3306'
  dbname: 'school'
  username: 'root'
  password: 'Aa@123456'

gin:
  host: '0.0.0.0'
  port: '80'
  debug: false

log:
  outputfile: true
  logname: 'error.log'
  logprefix: '[love-html]'

local:
  defaultmusic: 'http://youthsweet.com/file/危险派对.mp3'
  qqdefaultpic: 'http://youthsweet.com/file/危险派对.jpg'
  tips : '服务器出了点小意外。。。'
