mysql:
  hostname: '192.168.226.128'
  port: '3306'
  dbname: 'school'
  username: 'root'
  password: 'Aa@123456'

gin:
  host: '0.0.0.0'
  port: '80'
  debug: false

log:
  outputfile: true
  logname: 'error.log'
  logprefix: '[love-html]'

local:
  defaultmusic: 'http://39.101.203.25/file/%E9%87%91%E7%8E%89%E8%89%AF%E7%BC%98.m4a'
  qqdefaultpic: 'http://39.101.203.25/file/qqyy.jpg'
  tips : '服务器出了点小意外。。。'
