package model

type Netease1 struct {
	Code int `json:"code"`
	RelatedVideos interface{} `json:"relatedVideos"`
	Playlist struct {
		ID int `json:"id"`
		Name string `json:"name"`
		CoverImgID int64 `json:"coverImgId"`
		CoverImgURL string `json:"coverImgUrl"`
		CoverImgIDStr string `json:"coverImgId_str"`
		AdType int `json:"adType"`
		UserID int `json:"userId"`
		CreateTime int64 `json:"createTime"`
		Status int `json:"status"`
		OpRecommend bool `json:"opRecommend"`
		HighQuality bool `json:"highQuality"`
		NewImported bool `json:"newImported"`
		UpdateTime int64 `json:"updateTime"`
		TrackCount int `json:"trackCount"`
		SpecialType int `json:"specialType"`
		Privacy int `json:"privacy"`
		TrackUpdateTime int64 `json:"trackUpdateTime"`
		CommentThreadID string `json:"commentThreadId"`
		PlayCount int64 `json:"playCount"`
		TrackNumberUpdateTime int64 `json:"trackNumberUpdateTime"`
		SubscribedCount int `json:"subscribedCount"`
		CloudTrackCount int `json:"cloudTrackCount"`
		Ordered bool `json:"ordered"`
		Description string `json:"description"`
		Tags []interface{} `json:"tags"`
		UpdateFrequency interface{} `json:"updateFrequency"`
		BackgroundCoverID int `json:"backgroundCoverId"`
		BackgroundCoverURL interface{} `json:"backgroundCoverUrl"`
		TitleImage int `json:"titleImage"`
		TitleImageURL interface{} `json:"titleImageUrl"`
		EnglishTitle interface{} `json:"englishTitle"`
		OfficialPlaylistType interface{} `json:"officialPlaylistType"`
		Subscribers []struct {
			DefaultAvatar bool `json:"defaultAvatar"`
			Province int `json:"province"`
			AuthStatus int `json:"authStatus"`
			Followed bool `json:"followed"`
			AvatarURL string `json:"avatarUrl"`
			AccountStatus int `json:"accountStatus"`
			Gender int `json:"gender"`
			City int `json:"city"`
			Birthday int `json:"birthday"`
			UserID int64 `json:"userId"`
			UserType int `json:"userType"`
			Nickname string `json:"nickname"`
			Signature string `json:"signature"`
			Description string `json:"description"`
			DetailDescription string `json:"detailDescription"`
			AvatarImgID int64 `json:"avatarImgId"`
			BackgroundImgID int64 `json:"backgroundImgId"`
			BackgroundURL string `json:"backgroundUrl"`
			Authority int `json:"authority"`
			Mutual bool `json:"mutual"`
			ExpertTags interface{} `json:"expertTags"`
			Experts interface{} `json:"experts"`
			DjStatus int `json:"djStatus"`
			VipType int `json:"vipType"`
			RemarkName interface{} `json:"remarkName"`
			AuthenticationTypes int `json:"authenticationTypes"`
			AvatarDetail interface{} `json:"avatarDetail"`
			BackgroundImgIDStr string `json:"backgroundImgIdStr"`
			AvatarImgIDStr1 string `json:"avatarImgIdStr"`
			Anchor bool `json:"anchor"`
			AvatarImgIDStr2 string `json:"avatarImgId_str"`
		} `json:"subscribers"`
		Subscribed interface{} `json:"subscribed"`
		Creator struct {
			DefaultAvatar bool `json:"defaultAvatar"`
			Province int `json:"province"`
			AuthStatus int `json:"authStatus"`
			Followed bool `json:"followed"`
			AvatarURL string `json:"avatarUrl"`
			AccountStatus int `json:"accountStatus"`
			Gender int `json:"gender"`
			City int `json:"city"`
			Birthday int `json:"birthday"`
			UserID int `json:"userId"`
			UserType int `json:"userType"`
			Nickname string `json:"nickname"`
			Signature string `json:"signature"`
			Description string `json:"description"`
			DetailDescription string `json:"detailDescription"`
			AvatarImgID int64 `json:"avatarImgId"`
			BackgroundImgID int64 `json:"backgroundImgId"`
			BackgroundURL string `json:"backgroundUrl"`
			Authority int `json:"authority"`
			Mutual bool `json:"mutual"`
			ExpertTags interface{} `json:"expertTags"`
			Experts interface{} `json:"experts"`
			DjStatus int `json:"djStatus"`
			VipType int `json:"vipType"`
			RemarkName interface{} `json:"remarkName"`
			AuthenticationTypes int `json:"authenticationTypes"`
			AvatarDetail struct {
				UserType int `json:"userType"`
				IdentityLevel int `json:"identityLevel"`
				IdentityIconURL string `json:"identityIconUrl"`
			} `json:"avatarDetail"`
			BackgroundImgIDStr string `json:"backgroundImgIdStr"`
			AvatarImgIDStr1 string `json:"avatarImgIdStr"`
			Anchor bool `json:"anchor"`
			AvatarImgIDStr2 string `json:"avatarImgId_str"`
		} `json:"creator"`
		Tracks []struct {
			Name string `json:"name"`
			ID int `json:"id"`
			Pst int `json:"pst"`
			T int `json:"t"`
			Ar []struct {
				ID int `json:"id"`
				Name string `json:"name"`
				Tns []interface{} `json:"tns"`
				Alias []interface{} `json:"alias"`
			} `json:"ar"`
			Alia []string `json:"alia"`
			Pop int `json:"pop"`
			St int `json:"st"`
			Rt string `json:"rt"`
			Fee int `json:"fee"`
			V int `json:"v"`
			Crbt interface{} `json:"crbt"`
			Cf string `json:"cf"`
			Al struct {
				ID int `json:"id"`
				Name string `json:"name"`
				PicURL string `json:"picUrl"`
				Tns []interface{} `json:"tns"`
				PicStr string `json:"pic_str"`
				Pic int64 `json:"pic"`
			} `json:"al"`
			Dt int `json:"dt"`
			H struct {
				Br int `json:"br"`
				Fid int `json:"fid"`
				Size int `json:"size"`
				Vd int `json:"vd"`
			} `json:"h"`
			M struct {
				Br int `json:"br"`
				Fid int `json:"fid"`
				Size int `json:"size"`
				Vd int `json:"vd"`
			} `json:"m"`
			L struct {
				Br int `json:"br"`
				Fid int `json:"fid"`
				Size int `json:"size"`
				Vd int `json:"vd"`
			} `json:"l"`
			A interface{} `json:"a"`
			Cd string `json:"cd"`
			No int `json:"no"`
			RtURL interface{} `json:"rtUrl"`
			Ftype int `json:"ftype"`
			RtUrls []interface{} `json:"rtUrls"`
			DjID int `json:"djId"`
			Copyright int `json:"copyright"`
			SID int `json:"s_id"`
			Mark int `json:"mark"`
			OriginCoverType int `json:"originCoverType"`
			OriginSongSimpleData interface{} `json:"originSongSimpleData"`
			Single int `json:"single"`
			NoCopyrightRcmd interface{} `json:"noCopyrightRcmd"`
			Rtype int `json:"rtype"`
			Rurl interface{} `json:"rurl"`
			Mst int `json:"mst"`
			Cp int `json:"cp"`
			Mv int `json:"mv"`
			PublishTime int64 `json:"publishTime"`
			Tns []string `json:"tns,omitempty"`
		} `json:"tracks"`
		VideoIds interface{} `json:"videoIds"`
		Videos interface{} `json:"videos"`
		TrackIds []struct {
			ID int `json:"id"`
			V int `json:"v"`
			T int `json:"t"`
			At int64 `json:"at"`
			Alg interface{} `json:"alg"`
			UID int `json:"uid"`
			RcmdReason string `json:"rcmdReason"`
			Lr int `json:"lr,omitempty"`
			Ratio int `json:"ratio"`
		} `json:"trackIds"`
		ShareCount int `json:"shareCount"`
		CommentCount int `json:"commentCount"`
		RemixVideo interface{} `json:"remixVideo"`
		SharedUsers interface{} `json:"sharedUsers"`
		HistorySharedUsers interface{} `json:"historySharedUsers"`
		ToplistType string `json:"ToplistType"`
	} `json:"playlist"`
	Urls interface{} `json:"urls"`
	Privileges []struct {
		ID int `json:"id"`
		Fee int `json:"fee"`
		Payed int `json:"payed"`
		RealPayed int `json:"realPayed"`
		St int `json:"st"`
		Pl int `json:"pl"`
		Dl int `json:"dl"`
		Sp int `json:"sp"`
		Cp int `json:"cp"`
		Subp int `json:"subp"`
		Cs bool `json:"cs"`
		Maxbr int `json:"maxbr"`
		Fl int `json:"fl"`
		Pc interface{} `json:"pc"`
		Toast bool `json:"toast"`
		Flag int `json:"flag"`
		PaidBigBang bool `json:"paidBigBang"`
		PreSell bool `json:"preSell"`
		PlayMaxbr int `json:"playMaxbr"`
		DownloadMaxbr int `json:"downloadMaxbr"`
		Rscl interface{} `json:"rscl"`
		FreeTrialPrivilege struct {
			ResConsumable bool `json:"resConsumable"`
			UserConsumable bool `json:"userConsumable"`
		} `json:"freeTrialPrivilege"`
		ChargeInfoList []struct {
			Rate int `json:"rate"`
			ChargeURL interface{} `json:"chargeUrl"`
			ChargeMessage interface{} `json:"chargeMessage"`
			ChargeType int `json:"chargeType"`
		} `json:"chargeInfoList"`
	} `json:"privileges"`
	SharedPrivilege interface{} `json:"sharedPrivilege"`
	ResEntrance interface{} `json:"resEntrance"`
}

type Netease2 struct {
	Result struct {
		Songs []struct {
			Name string `json:"name"`
			ID int `json:"id"`
			Pst int `json:"pst"`
			T int `json:"t"`
			Ar []struct {
				ID int `json:"id"`
				Name string `json:"name"`
				Tns []interface{} `json:"tns"`
				Alias []string `json:"alias"`
				Alia []string `json:"alia"`
			} `json:"ar"`
			Alia []string `json:"alia"`
			Pop int `json:"pop"`
			St int `json:"st"`
			Rt interface{} `json:"rt"`
			Fee int `json:"fee"`
			V int `json:"v"`
			Crbt interface{} `json:"crbt"`
			Cf string `json:"cf"`
			Al struct {
				ID int `json:"id"`
				Name string `json:"name"`
				PicURL string `json:"picUrl"`
				Tns []interface{} `json:"tns"`
				PicStr string `json:"pic_str"`
				Pic int64 `json:"pic"`
			} `json:"al"`
			Dt int `json:"dt"`
			H interface{} `json:"h"`
			M struct {
				Br int `json:"br"`
				Fid int `json:"fid"`
				Size int `json:"size"`
				Vd int `json:"vd"`
			} `json:"m"`
			L struct {
				Br int `json:"br"`
				Fid int `json:"fid"`
				Size int `json:"size"`
				Vd int `json:"vd"`
			} `json:"l"`
			A interface{} `json:"a"`
			Cd string `json:"cd"`
			No int `json:"no"`
			RtURL interface{} `json:"rtUrl"`
			Ftype int `json:"ftype"`
			RtUrls []interface{} `json:"rtUrls"`
			DjID int `json:"djId"`
			Copyright int `json:"copyright"`
			SID int `json:"s_id"`
			Mark int `json:"mark"`
			OriginCoverType int `json:"originCoverType"`
			OriginSongSimpleData interface{} `json:"originSongSimpleData"`
			ResourceState bool `json:"resourceState"`
			Version int `json:"version"`
			Single int `json:"single"`
			NoCopyrightRcmd interface{} `json:"noCopyrightRcmd"`
			Rtype int `json:"rtype"`
			Rurl interface{} `json:"rurl"`
			Mst int `json:"mst"`
			Cp int `json:"cp"`
			Mv int `json:"mv"`
			PublishTime int64 `json:"publishTime"`
			Privilege struct {
				ID int `json:"id"`
				Fee int `json:"fee"`
				Payed int `json:"payed"`
				St int `json:"st"`
				Pl int `json:"pl"`
				Dl int `json:"dl"`
				Sp int `json:"sp"`
				Cp int `json:"cp"`
				Subp int `json:"subp"`
				Cs bool `json:"cs"`
				Maxbr int `json:"maxbr"`
				Fl int `json:"fl"`
				Toast bool `json:"toast"`
				Flag int `json:"flag"`
				PreSell bool `json:"preSell"`
				PlayMaxbr int `json:"playMaxbr"`
				DownloadMaxbr int `json:"downloadMaxbr"`
				Rscl interface{} `json:"rscl"`
				FreeTrialPrivilege struct {
					ResConsumable bool `json:"resConsumable"`
					UserConsumable bool `json:"userConsumable"`
				} `json:"freeTrialPrivilege"`
				ChargeInfoList []struct {
					Rate int `json:"rate"`
					ChargeURL interface{} `json:"chargeUrl"`
					ChargeMessage interface{} `json:"chargeMessage"`
					ChargeType int `json:"chargeType"`
				} `json:"chargeInfoList"`
			} `json:"privilege"`
			Tns []string `json:"tns,omitempty"`
		} `json:"songs"`
		SongCount int `json:"songCount"`
	} `json:"result"`
	Code int `json:"code"`
}

type Netease3 struct {
	Data []struct {
		ID int `json:"id"`
		URL string `json:"url"`
		Br int `json:"br"`
		Size int `json:"size"`
		Md5 string `json:"md5"`
		Code int `json:"code"`
		Expi int `json:"expi"`
		Type string `json:"type"`
		Gain int `json:"gain"`
		Fee int `json:"fee"`
		Uf interface{} `json:"uf"`
		Payed int `json:"payed"`
		Flag int `json:"flag"`
		CanExtend bool `json:"canExtend"`
		FreeTrialInfo interface{} `json:"freeTrialInfo"`
		Level string `json:"level"`
		EncodeType string `json:"encodeType"`
		FreeTrialPrivilege struct {
			ResConsumable bool `json:"resConsumable"`
			UserConsumable bool `json:"userConsumable"`
		} `json:"freeTrialPrivilege"`
		FreeTimeTrialPrivilege struct {
			ResConsumable bool `json:"resConsumable"`
			UserConsumable bool `json:"userConsumable"`
			Type int `json:"type"`
			RemainTime int `json:"remainTime"`
		} `json:"freeTimeTrialPrivilege"`
		URLSource int `json:"urlSource"`
	} `json:"data"`
	Code int `json:"code"`
}